### ISSUE TITLE
is devise_invitable supported? (solvable with workaround)

### ISSUE THREAD

**Issue by salmanasiddiqui** [lynndylanhurley/devise_token_auth#155] opened 2015-02-17 10:22 UTC
I am trying to use devise_invitable(1.4.0) gem with devise_token_auth(0.1.31)/devise(3.4.1) but having an issue. When I make a post request to auth/invitation the following error occurs

```
ArgumentError in Devise::InvitationsController#create
wrong number of arguments (1 for 0)

Extracted source (around line #102):
101        class_eval <<-METHODS, __FILE__, __LINE__ + 1
102          def authenticate_#{mapping}!
103            unless current_#{mapping}
104              return render json: {
105                errors: ["Authorized users only."]

Trace:
devise_token_auth (0.1.31) lib/devise_token_auth/controllers/helpers.rb:102:in `authenticate_user!'
devise_invitable (1.4.0) lib/devise_invitable/controllers/helpers.rb:18:in `authenticate_inviter!'
devise_invitable (1.4.0) app/controllers/devise/invitations_controller.rb:69:in `current_inviter'
devise_invitable (1.4.0) app/controllers/devise/invitations_controller.rb:73:in `has_invitations_left?'
```

First I setup devise_token_auth and is working perfectly. Now I am adding devise_invitable as follows:
1) Passed parameter `:invitable` in user model `devise` method
2) Executed migraton to add devise_invitable columns

that's it, running `rake routes` shows me that devise_token_auth is creating routes for invitation. But they are showing me above posted error.

Is devise_invitable is supported by devise_token_auth? Is there a way to use them together?

**Comment by lynndylanhurley** [comment] 2015-02-17 17:50
@salmanasiddiqui - I haven't looked into this yet, and I'm not sure what devise_invitable support will entail. I'll look into this as soon as I get a chance.

**Comment by mchavarriagam** [comment] 2015-04-09 04:32
+1

I've been looking at the code for a while and I've identified a few things that I _think_ will need to be updated in order for this to run. I've been able to replicate @salmanasiddiqui's issue but I haven't yet figured out *why* it's happening. One thing to keep in mind is that devise_invitable does
```prepend_before_filter :authenticate_inviter!, :only => [:new, :create]```
which means that authenticate_inviter will have to be locally overridden to call set_user_by_token and return the authenticated user, which is expected by the invitable controller (check https://github.com/scambra/devise_invitable -> Controller Filter section for more info).

I can work on a pull request if I manage to figure out the issue.

**Comment by mchavarriagam** [comment] 2015-04-09 05:26
I forgot to add version info:

DTA -> v0.1.32.beta9
Devise -> v3.4.1
devise_invitable -> v1.4.2

**Comment by mchavarriagam** [comment] 2015-04-09 05:38
I think the reason why this is happening is not really because of proxy delegation (the "proxy" on DeviseController's resource_class threw me off track) but simply because the scope of the call is set to InvitationController which inherits from DeviseController, so when resource_class is called from set_user_by_token (itself being called from InvitationController through a before_filter defined in ApplicationController), the scope determines that it will be DeviseController's resource_class that gets called instead.

**Comment by mchavarriagam** [comment] 2015-04-09 07:17
As it turns out, moving ```include DeviseTokenAuth::Concerns::SetUserByToken``` to a controller that inherits from Devise::InvitationsController (instead of having it on ApplicationController) solves the issue (though it raises the issue of having to repeat the SetUserByToken inclusion in all controllers throughout the site; messy). You guys probably know why but here's what I found, just in case:

1. Devise::InvitationsController inherits from DeviseController, which has a resource_class method (no arguments) -> [here](https://github.com/scambra/devise_invitable/blob/3d64d781cd8561e9372e06648a203ff12e998cc2/app/controllers/devise/invitations_controller.rb#L1).
2. Devise::InvitationsController forces authenticate_inviter as a before_filter, which has to be overriden with a call to SetUserByToken instead [here](https://github.com/scambra/devise_invitable/blob/3d64d781cd8561e9372e06648a203ff12e998cc2/app/controllers/devise/invitations_controller.rb#L3).
3. The way that this is recommended (in devise_invitable's documentation, [here](https://github.com/scambra/devise_invitable) go to "Controller Filter" section) is to override the method in ApplicationController.
4. If done this way, SetUserByToken Concern will end up being inserted after ApplicationController in the inheritance chain, and DeviseController's resource_class will end up being evaluated before SetUserByToken's, which results in the error we were experiencing.

Thoughts?

**Comment by lynndylanhurley** [comment] 2015-04-09 15:37
@mchavarriagam - thanks for taking the time to look into this.

As you've found out by now, this one is tricky. I'll have some time early next week to dig in. If you can solve it in the meantime, please send me a PR (with tests!!).

**Comment by mchavarriagam** [comment] 2015-04-09 15:47
Sure thing! I'll work on a PR (with tests!!) later today and should have something ready before end of week. Thanks for the gem, it's been great working it with so far. :D

**Comment by salmanasiddiqui** [comment] 2015-04-10 07:36
@mchavarriagam 

actually `authenticate_inviter!` calls the `authenticate_user!`(authenticate_#{mapping}!) method. The `authenticate_#{mapping}!` method defined in devise_token_auth doesnt take any parameters.. while in devise it does take parameter `opts={}` -> [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/controllers/helpers.rb#L102) vs [devise](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/helpers.rb#L110)

so just by adding the parameter in devise_token_auth, will resolve this issue..
DeviseInvitation calls `authenticate_inviter!` which calls `authenticate_user!` of devise_token_auth, and that calls `current_user`, which calls `set_user_by_token(:user)` itself. -> [here](https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/devise_token_auth/controllers/helpers.rb#L114)

but even after this I faced several other issues, dont remember each of them now though..
here is my [Invitation Controller](https://gist.github.com/salmanasiddiqui/c5b8fed03757e4a2fbd0) in the app.
and here are the modifications I did in [Devise Token Auth](https://github.com/lynndylanhurley/devise_token_auth/compare/master...salmanasiddiqui:master) and using this in my app.

the above is surely missing many things of devise token auth.. as I m still getting my head around it.. and I was really short on time when I did it..

**Comment by mchavarriagam** [comment] 2015-04-10 13:00
Nice! Thanks for going over that, it makes things a lot clearer now.

I see that you also updated routes.rb by adding invitations_ctrl. The approach that I tried was to do a merge of the opts[:controllers] into controllers right before going through the "skip" part ([here](https://github.com/lynndylanhurley/devise_token_auth/blob/ca13ee2d1344cbe585d32927d869a2e316beb064/lib/devise_token_auth/rails/routes.rb#L24)). That way any controller that's included in opts[:controller] will make it into the final list of controllers (without having to hard-code invitations_ctrl in there).

Thanks again for sharing that info, it'll make it easier for me to work on the PR.

**Comment by salmanasiddiqui** [comment] 2015-04-13 05:46
actually what I tried, I simply defaulted the routes for invitation controller to devise Invitation controller and then overridden that controller in my app in a way similar to confirmation controller and password controller in devise token auth.

the devise token auth way to do this would be, to rewrite this controller in devise token auth, and then routes should by defaulted to that.

Im also kind of confused by the way devise token auth works and written. Why routes are defaulted to devise token auth? Is it not possible to achieve this token based authentication by simply overriding the devise controllers by inheriting from it?

devise token auth inherits from the base devise controller and then defines his own child controllers.. Rails community is quite familiar with the devise, so imo it might be better to override those controllers by inheriting from those controllers directly, use the same filters as devise uses but override them as needed? or skip few of them if not needed?

just putting out my thoughts, @lynndylanhurley what do you think?

Also, I think each version of devise token auth should mention the compatible ng token auth version and vice versa? or their version should be kept same?

**Comment by fertingoff** [comment] 2015-06-15 14:31
@mchavarriagam, any hopes for pr? :)

**Comment by mchavarriagam** [comment] 2015-06-15 15:06
@fertingoff sorry, been really busy lately so I haven't been able to get back to this. Will probably get some time next week but I can't promise anything right now. Apologies for that.

**Comment by fertingoff** [comment] 2015-06-15 15:39
@mchavarriagam, awesome, thank's a lot! Take your time.

P.S. You just helped me to have a good sleep tonight :full_moon_with_face:

**Comment by fertingoff** [comment] 2015-07-03 15:35
@mchavarriagam, please, let me know if you change your mind :)

**Comment by mchavarriagam** [comment] 2015-07-03 15:42
:D I'm planning on working on it this weekend, since I finally have some time off. I may ask you guys a few questions over here so we can bounce ideas off each other.

**Comment by fertingoff** [comment] 2015-07-18 08:16
hi @mchavarriagam! 
I cant figure out this by myself so far. what do you think, is it still real or it will take more much more time?
Thanks again for you possible help.

**Comment by gabrielhilal** [comment] 2015-08-11 14:23
I'm facing the same issue... any news on that?

**Comment by mchavarriagam** [comment] 2015-08-11 14:29
I haven't had any luck in making my approach work so far and it's taking me longer than I anticipated, definitely. I don't think a solution is coming any time soon. Sorry guys.

**Comment by gabrielhilal** [comment] 2015-08-11 16:42
My workaround in case someone else is facing the problem:

routes.rb:

```
namespace :api do
  mount_devise_token_auth_for 'User', at: 'auth', skip: [:invitations],
    controllers: { registrations: 'api/registrations' }
  devise_for :users, path: "auth", only: [:invitations],
    controllers: { invitations: 'api/invitations' }
end
```

invitations_controller:

```
module Api
  class InvitationsController < Devise::InvitationsController

    private

    def authenticate_inviter!
      authenticate_user!
    end

    def authenticate_user!
      unless current_user
        return render json: {
          errors: ["Authorized users only."]
        }, status: 401
      end
    end

    def resource_class(m=nil)
      if m
        mapping = Devise.mappings[m]
      else
        mapping = Devise.mappings[resource_name] || Devise.mappings.values.first
      end
      mapping.to
    end

  end
end
```

**Comment by mchavarriagam** [comment] 2015-08-11 16:49
_sweet!_

**Comment by fertingoff** [comment] 2015-08-28 06:18
@gabrielhilal thanks for posting this workaround. I'm trying to implement it, but have several questions and would appreciate your help. 

1. As far as I understand you use your custom registrations_controller (`controllers: { registrations: 'api/registrations' }`). Why you use it instead of registrations_controller from devise_token_auth  and what is the difference between them in your case?
2. How does you your invitation link look like? Devise_invitable by default generates something like this: `http://localhost:3000/api/v1/auth/invitation/accept?invitation_token=tQ9ss2T-dcD6rNNcFTLc`. Should it have `redirect_url` or other parameters and if yes what method does it in your case?
3. By default a link from email is processed by devise_invitable's InvitationsController#edit:
```
 # GET /resource/invitation/accept?invitation_token=abcdef
  def edit
    resource.invitation_token = params[:invitation_token]
    render :edit
  end
``` 
However, it doesn't work, since it is for solid rails app, right? I assume that either I need to change this method or I need to redirect to other method. From a gist you posted above I see that you changed nothing except three private methods. So, how come your app works? :)
4. All in all I hope to find myself at a page of setting new password in my angular app. My 'educated guess' is that the route should be http://localhost:9000/#/reset_password (for localhost) with confirmed token by devise_invitable. What method and when does this in your case if my guess is correct?

Thank you very much.

**Comment by gabrielhilal** [comment] 2015-08-28 13:36
Hi @fertingoff, let's see if I can help answering your questions:

1- The `registrations_controller` has nothing to do with this invitable issue. I have overrode some actions because of my requirements... sorry for the copy and paste of my `routes`... do no worry about that ;)

2 and 3- My invitation link is `http://localhost:3000/api/auth/invitation/accept?invitation_token=xxxx`, so if you have the `v1` your link looks fine... I have not included the `redirect_url`  because in my case I will always redirect to the same place. So, I'm doing the redirect in the edit action:
```
# api/invitations_controller (devise override)
def edit
  redirect_to "#{my_url}?invitation_token=#{params[:invitation_token]}"
end
```
You will have to change some more methods if you want to send the `redirect_url` to the mailer...

4- My edit action redirects to the set password form (angular), sending the `invitation_token` param.
So, your angular has to PUT or PATCH the `invitation_token`, as well as the `password` and `password_confirmation` to `/api/auth/invitation`. I think  `/api/auth/v1/invitation` in your case.

I really hope it helps :)

In case I forgot something, please note the controller example below ;)
```
class InvitationsController < Devise::InvitationsController
  include InvitableMethods # methods that I posted in the previous answer
  before_action :resource_from_invitation_token, only: :update

  def create
    @user = User.invite!(invite_params, current_user)
    render json: { success: ['User created.'] }, status: :created
  end

  def edit
    redirect_to "#{my_url}?invitation_token=#{params[:invitation_token]}"
  end

  def update
    @user = User.accept_invitation!(accept_invitation_params)
    if @user.errors.empty?
      render json: { success: ['User updated.'] }, status: :accepted
    else
      render json: { errors: @user.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  private

  def invite_params
    params.permit(user:
      [:first_name, :last_name, :job_title, :mobile_number,
       :email, :invitation_token, :provider, :skip_invitation])[:user]
  end

  def accept_invitation_params
    params.permit(:password, :password_confirmation, :invitation_token)
  end
end

**Comment by fertingoff** [comment] 2015-08-28 16:27
Hi @gabrielhilal, thank you for your prompt and comprehensive reply. It helped a lot. 
After successfully firing InvitationsController#update I have a user with updated :encrypted_password field (the only sign of success for me alongside with `render json: { success: ['User updated.'] }, status: :accepted`). The next step as far as I see is just to sign_in in order to get token. But for some reason I have `bad credentials` error. Is my way of thinking correct?
Thx again!

**Comment by gabrielhilal** [comment] 2015-08-28 18:50
Hi @fertingoff, after the update action you should be able to sign in... 
Make sure you have the following fields in the users table:
```
## Invitable
t.string   :invitation_token
t.datetime :invitation_created_at
t.datetime :invitation_sent_at
t.datetime :invitation_accepted_at
t.integer  :invitation_limit
t.integer  :invited_by_id
t.string   :invited_by_type
```
Also, make sure the `invitation_accepted_at` is updated as well (after the update action).

And just one more thing, make sure you are using the `raw_invitation_token` in the email view:

`<p><%= link_to 'Accept invitation', accept_api_v1_user_invitation_url(invitation_token: @resource.raw_invitation_token) %></p>`

I hope it helps ;)

**Comment by fertingoff** [comment] 2015-08-31 05:51
Thank you @gabrielhilal. You empowered me.
Eventually it works.

*Just for the records. In my case the problem was that instance of a user need to have uid (email) and provider('email')*

**Comment by klm88** [comment] 2015-12-01 19:10
Will devise_invitable support be added to this gem anytime soon or do we need to implement the workaround?

**Comment by gabrielhilal** [comment] 2015-12-01 19:50
I wrote a post about the issue and my solution (workaround)... it might be useful to someone, so will leave the link here:  http://gabrielhilal.com/2015/11/07/integrating-devise_invitable-into-devise_token_auth/

**Comment by ashwinputhige** [comment] 2016-02-02 07:05
This worked for me.
To invite an use : 
```user = User.invite!({:email => "users_email_here"})```

I edited the URL in the invitation email to include the token after "#"
```http://localhost:3000/#/accept/V396a4Kz1aiGdnVwR ```

Added an angular route to handle that URL and accepted the invitation in my controller.
```
user = User.accept_invitation!(:password => password,
       :password_confirmation => password_confirmation,
       :invitation_token => invitation_token)
```

**Comment by zachfeldman** [comment] 2017-10-06 13:24
Hi there @salmanasiddiqui ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Comment by salmanasiddiqui** [comment] 2017-10-06 15:05
@zachfeldman ,

Before this issue is closed, I would propose to make a simple change in `devise_token_auth`

Fix the signature of  `authenticate_#{mapping}!` method.
In Devise `authenticate_#{mapping}!` method accepts 1 argument `opts`. As `devise_token_auth` 's intention is to override this method hence the signature should be same.

**Comment by zachfeldman** [comment] 2017-10-14 14:36
Let's see what @MaicolBen and/or @lynndylanhurley think!

**Comment by zachfeldman** [comment] 2017-10-14 14:36
I don't have an objection to it.

**Comment by lynndylanhurley** [comment] 2017-10-14 17:53
> Fix the signature of authenticate_#{mapping}! method.
In Devise authenticate_#{mapping}! method accepts 1 argument opts. As devise_token_auth 's intention is to override this method hence the signature should be same.
>
> Let me know if you agree, I can make the PR

@salmanasiddiqui please make a PR and we will review ASAP. Thanks!

**Comment by ilhanadiyaman** [comment] 2017-11-21 01:31
I have the same issue. @salmanasiddiqui any progress for the PR?

**Comment by salmanasiddiqui** [comment] 2017-11-28 09:57
Made the PR. I haven't added any tests, though I would suggest that all the tests for this specific helper in `Devise` should be copied over. I have moved to python for the past few months and don't have ruby configured. 🙁

**Comment by zachfeldman** [comment] 2017-11-28 14:38
This PR doesn't appear that it would break anything because the method has a default argument, so I merged it.

**Comment by MaicolBen** [comment] 2017-11-28 14:42
Can this be closed?

**Closed** 2017-11-28 14:44 UTC

**Comment by ccoeder** [comment] 2018-09-18 10:40
Hi @gabrielhilal,

> 2 and 3- My invitation link is http://localhost:3000/api/auth/invitation/accept?invitation_token=xxxx, so if you have the v1 scope your link looks fine... I have not included the redirect_url because in my case I will always redirect to the same place. So, I'm doing the redirect in the edit action:

I want to add redirect_url to invitations, how can I do that? Can you help me?
