### ISSUE TITLE
On sign_in, devise_token_auth expects the uid to be the same as the email

### ISSUE THREAD

**Issue by mattSpell** [lynndylanhurley/devise_token_auth#237] opened 2015-05-08 13:05 UTC
I am using the rails-api gem,  devise_token_auth (0.1.30) and ng-token-auth "0.0.24".
When I try to log in, this is the dev.log:

```
Started POST "/api/auth/sign_in" for 127.0.0.1 at 2015-05-07 13:44:05 -0500
  [1m[36mActiveRecord::SchemaMigration Load (0.3ms)[0m  [1mSELECT "schema_migrations".* FROM "schema_migrations"[0m
Processing by DeviseTokenAuth::SessionsController#create as HTML
  Parameters: {"email"=>"b@b.com", "password"=>"[FILTERED]"}
  [1m[35mUser Load (2.0ms)[0m  SELECT  "users".* FROM "users"  WHERE (uid='b@b.com' AND provider='email')  ORDER BY "users"."id" ASC LIMIT 1
Completed 401 Unauthorized in 8ms (Views: 0.2ms | ActiveRecord: 3.8ms)
```

Here is a shot of the req/res headers:

![headers](https://cloud.githubusercontent.com/assets/5875695/7552327/e8ab087c-f673-11e4-90cc-7341e113b428.png)

Does anyone know why it expects the uid to be the email? (quoted from the dev.log) `SELECT  "users".* FROM "users"  WHERE (uid='b@b.com' AND provider='email')`

The only way I can get my login to work is by changing my model to `self.uid = self.email` but I'd rather not have to do that. Any help would be greatly appreciated.

**Comment by jasonswett** [comment] 2015-05-11 16:29
+1

**Comment by oniofchaos** [comment] 2015-06-01 21:48
+1

**Comment by arvinkx** [comment] 2015-07-15 19:17
Are you using the confirmable module? I ran into the same (I was changing my uid from the email to a random uuid) and was getting the 401 with the correct email and password but the account had not been confirmed yet. Once I confirmed the account through the email link it no longer attempted to use the uid to search the db, it used the email.

**Comment by arvinkx** [comment] 2015-07-15 19:21
Are you using the confirmable module? I ran into the same issue (I was changing the uid to a random uuid) but after confirming the account (clicking the link in the email) the account works fine (uses email to search db for the email address instead of the uid field).

**Comment by arvinkx** [comment] 2015-07-15 21:05
+1

**Comment by arvinkx** [comment] 2015-07-15 21:08
+1, I've tried to get the uid to be something other than email but it seems that without overriding alot of the built-in functionality this isn't currently possible. It would be great, and I think safer, if we were able to use something more random, like uuid instead of the email. Is this something that's possible?

**Comment by booleanbetrayal** [comment] 2015-07-15 21:18
the `uid` field is the value that should map directly to the globally unique `provider` value. I guess the more important question is why are your `email` and `uid` values de-sync'd when using `email` as the provider?

**Comment by arvinkx** [comment] 2015-07-15 21:24
Thanks for the reply, I don't think I understand the role that provider plays... Am I correct in thinking the provider value is the name of the globally unique field to be used?

**Comment by booleanbetrayal** [comment] 2015-07-15 21:31
there's a little more to that because of [omniauth](https://github.com/intridea/omniauth) integration. For omniauth, the provider value will be something like **facebook** or **google**, etc. So in those cases, they're not mapped to local fields.

**Comment by arvinkx** [comment] 2015-07-15 22:12
So would simply changing the provider value to say a newly created local field called "uuid" achieve what we are trying to achieve? I'd like to still use email to validate for login but token validation to happen using the uuid value instead of exposing the email address? I assumed there would be alot of overrides needed especially for other controllers (confirmations, etc) due this change, is there a simpler approach than that? Thanks again for taking time to answer.

**Comment by arvinkx** [comment] 2015-07-15 23:29
Actually stumbled across https://github.com/lynndylanhurley/devise_token_auth/issues/29#issuecomment-56090454 and it doesn't seem like this can be done without a bit of further customization.

**Comment by booleanbetrayal** [comment] 2015-07-16 02:31
Going to go ahead and close this, as SessionsController needs the uid to be the email to support email-based sign-ins, and the current scheme relies on uid to be utilized based on provider context as explained. If we want to change the uid / provider scheme, I think that's a separate discussion.

**Closed by booleanbetrayal** 2015-07-16 02:31 UTC

**Comment by poc7667** [comment] 2016-04-22 13:22
@mattSpell  Hi this is how I workaround with this problem

```
class RegistrationsController < Devise::RegistrationsController
  def new
    super do |user|
    end
  end

  def create
    if params["user"]["uid"]==nil and  params["user"]["provider"]==nil
      configure_permitted_parameters
      params["user"]["uid"] = params["user"]["email"]
      params["user"]["provider"] = Rails.application.class.to_s.split("::").first # Application name
    end
    super # continue the dflt creation process
  end

  def update
    super
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push(:uid, :provider)
    end
end 
```
