### ISSUE TITLE
Cannot send confirmation email when using alongside with standard devise

### ISSUE THREAD

**Issue by ysyyork** [lynndylanhurley/devise_token_auth#456] opened 2015-11-30 00:41 UTC
I want to use standard devise alongside with devise token auth. When signing up users with standard devise, I found the confirmation email cannot be sent. However, email works well when signing up with devise token auth.  #229 discussed something about this but as a noob, unfortunately, I cannot understand what's going on here as the discussion is so short. Is there a way to enable email confirmation when using standard devise? I believe this happens because devise token gem modifies some parts of the registration controller in standard devise.

**Comment by zentetsukenz** [comment] 2015-12-23 15:01
I see the code here https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L121
states that  "this must be done from the controller so that additional params can be passed on from the client"

So, the quick fix would be add the method called `send_confirmation_notification?` and return true to your user's model.

But the problem is I cannot find any documentation here about `send_confirmation_notification?`. Would be nice if someone explain more about this.

**Comment by adisos** [comment] 2016-06-27 16:05
I ended up using this gist:
https://gist.github.com/adisos/248da0b1a520b8d85726c2ec224d885e

**Comment by zachfeldman** [comment] 2017-10-07 14:17
Sounds like we have a solution, so closing this for now.

**Closed by zachfeldman** 2017-10-07 14:17 UTC

**Comment by mbandrewfoster** [comment] 2019-05-20 15:01
So that gist is gone, what was the actual solution?

**Comment by webzorg** [comment] 2019-12-11 17:59
defining this method inside `devise_token_auth` like this ```def send_confirmation_notification?; false; end``` is OUTRAGEOUS!
