### ISSUE TITLE
Filter chain halted as :authenticate_user! rendered or redirected 

### ISSUE THREAD

**Issue by ask4ralph** [lynndylanhurley/devise_token_auth#935] opened 2017-08-04 00:13 UTC
This issue happens randomly when the following is set (which is the default): 
config.change_headers_on_each_request = true

...
Processing by Api::V1::UsersController#index as HTML
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2  [["uid", "test@test.com"], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2  [["uid", "test@test.com"], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2  [["uid", "test@test.com"], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.09ms)
Filter chain halted as :authenticate_user! rendered or redirected
Completed 401 Unauthorized in 22ms (Views: 4.6ms | ActiveRecord: 0.5ms)```

**Comment by lynndylanhurley** [comment] 2017-08-04 04:00
What is the issue?

**Comment by ask4ralph** [comment] 2017-08-04 11:14
Hi,
The user randomly gets an unauthorized response and randomly gets kicked out as you can see from the logs, it returns a 401.

This happens randomly - 1 out of 50 requests.

Regards

**Comment by zachfeldman** [comment] 2017-10-07 18:34
@ask4ralph can you post a sample repository where we can replicate this in order to help debug it? Otherwise I'm going to close this out in 7 days (we're cleaning up the repo). Thanks!

**Comment by MaicolBen** [comment] 2017-10-13 02:09
Closing as it's a duplicate of #51 and #359

**Closed by MaicolBen** 2017-10-13 02:09 UTC
Labels: close-in-7-days
