### ISSUE TITLE
getting random "Authorized users only." when uploading multiple files at once.

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/devise_token_auth#862] opened 2017-04-05 05:28 UTC
This only happen when I am trying to upload 15, 20 files at the time. And I don't know if this is due to the timeout. But most of the api response is 200. But some fail and return "Authorized users only.".

But I am always still logged in ? Any idea ? Also this seems to happen only in production mode.

Thank you.

![image](https://cloud.githubusercontent.com/assets/4422555/24691101/49328472-1986-11e7-9060-0aff7932e32c.png)

**Comment by AvaelKross** [comment] 2017-04-13 01:04
Maybe it is caused by this https://github.com/lynndylanhurley/devise_token_auth#about-batch-requests ? So some requests are invalid because the token is changed already? Try increasing `batch_request_buffer_throttle` parameter in `config/initializers/devise_token_auth.rb`

**Comment by zachfeldman** [comment] 2017-10-07 18:05
Closing in favor of #702

**Closed by zachfeldman** 2017-10-07 18:05 UTC
