### ISSUE TITLE
Confirming an already confirmed user -- still not quite working.

### ISSUE THREAD

**Issue by Evan-M** [lynndylanhurley/devise_token_auth#1123] opened 2018-03-22 20:24 UTC
_**NOTE:** Much of this has been referenced before in several different Issues and PRs, which I will attempt to link to. If I've left any out, I apologize in advance._

-------

Although it appears that this was first noted in either #410 or #519, and eventually merged in #1001, the current behavior is still not great.

After confirming a user's email address, I can continue to click the confirmation link (i.e. make GET requests to the `/auth/confirmations` endpoint, triggering the `devise_token_auth/confirmations#show` action).  It seems that the current behavior will generate a _new_ auth token for the user, and redirect to the successful confirmation URL (either from the params if present, or the `DeviseTokenAuth.default_confirm_success_url`).  

As pointed out in #1064, #1067, and #1075, when the _new_ token is created, it conditionally adds a expiration if the user has signed in (the `:sign_in_count` attribute), which creates a dependency on `:trackable`. And while #1064 + #1061 effectively uncouple the dependency, the result is that if `:trackable` is not included, then no expiration is set on the token! What-the-huh!!?

The confirmation process _should_ happen in a consistent manner, regardless of the presence of the `:trackable` module.  A review of the Devise internals shows that checking if a user has signed in (i.e. `@resource.has_attribute?(:sign_in_count) && @resource.sign_in_count > 0`) is **not an indicator of the user having been confirmed!**  Rather, it is the presence of a timestamp in the `:confirmed_at` attribute that indicates if a user has confirmed their account. (See: [`Devise::Models::Confirmable#confirm`] and [`Devise::Models::Confirmable#confirmed?`])

Furthermore, the [`Devise::ConfirmationsController#show`] action simply and concisely checks for the presence of validation errors on the user resource, as it handles checking for already confirmed users at the model level. (The [`Devise::Models::Confirmable#confirm`] method sets errors on the user's `:email` attribute, if that user has already been confirmed).

We're already using the same [`Devise::Models::Confirmable::ClassMethods#confirm_by_token`] method in: https://github.com/lynndylanhurley/devise_token_auth/blob/38d27cfa80042c184c6f69e74c0789ca8ec0e407/app/controllers/devise_token_auth/confirmations_controller.rb#L3-L4

Therefore, it _shouldn't_ really be necessary to check for specific attributes (or their values) on the user instance (e.g. `:sign_in_count`, `:confirmed_at`, etc...); just check for errors on the returned user instance like the [`Devise::ConfirmationsController#show`] action does.  The question is, _what_ does a failure response from the controller action look like?  It currently is just a 404 `Not Found`, but presumably it would call `DeviseTokenAuth::ApplicationController#render_error`, passing in the relevant validation errors where appropriate.

Lastly, it seems like the tests in the `confirmations_controller_test.rb` _not_ actually test most model level attributes; instead the tests should assert that various requests (each in known states) lead to the correct set of controller responses given those states.

Specifically, the tests for `:trackable` attributes should not exist at all here:
https://github.com/lynndylanhurley/devise_token_auth/blob/38d27cfa80042c184c6f69e74c0789ca8ec0e407/test/controllers/devise_token_auth/confirmations_controller_test.rb#L55-L65

And additional tests are needed to check the various possible validation errors on the user that _could_ happen when calling [`Devise::Models::Confirmable::ClassMethods#confirm_by_token`].

--------

I do intend on making a PR for all this, but I'm hoping to collect some feedback in the meantime. 

[`Devise::Models::Confirmable#confirm`]: https://github.com/plataformatec/devise/blob/75f9e76f65d2fd9892631efd0221ebe1921344b7/lib/devise/models/confirmable.rb#L76-L103
[`Devise::Models::Confirmable#confirmed?`]: https://github.com/plataformatec/devise/blob/75f9e76f65d2fd9892631efd0221ebe1921344b7/lib/devise/models/confirmable.rb#L105-L108
[`Devise::Models::Confirmable::ClassMethods#confirm_by_token`]: https://github.com/plataformatec/devise/blob/75f9e76f65d2fd9892631efd0221ebe1921344b7/lib/devise/models/confirmable.rb#L343-L360 
[`Devise::ConfirmationsController#show`]: https://github.com/plataformatec/devise/blob/75f9e76f65d2fd9892631efd0221ebe1921344b7/app/controllers/devise/confirmations_controller.rb#L21-L32

**Comment by Evan-M** [comment] 2018-03-26 17:35
@lynndylanhurley, @MaicolBen, @zachfeldman, @dks17, @KelseyDH, thoughts? ☝️ 
(Any feedback appreciated from all!)

**Comment by MaicolBen** [comment] 2018-03-26 18:03
>  the result is that if :trackable is not included, then no expiration is set on the token!
Agreed with that, it's awful.

And agreed with your planned changes. If with `resource.errors.empty?` is enough to check if the user already confirmed, go ahead with the change.

I prefer e2e tests like [rspec request tests](http://matthewlehner.net/rails-api-testing-guidelines/) because they don't depend on internals, but it's hard to migrate the current test suite.

**Comment by dks17** [comment] 2018-03-27 07:10
Question. Is the life cycle of the current version coming at the end and to go further new version of this gem should be released with reconsidering workflow, rspec, resolved issues (and, ofcourse new ones) and etc?

**Comment by MaicolBen** [comment] 2018-03-27 13:41
We aren't planning to change the current workflow, the next big milestone is #990 and it should work with the current workflow. If you have in mind a different workflow, open an issue and we discuss it.

**Comment by dikond** [comment] 2018-05-24 13:02
To maintainers - thank you all for the gem and efforts to keep it up!
@Evan-M Thanks for bringing it all together 👍 And a special thank you for discovering race condition which you described [here](https://github.com/lynndylanhurley/devise_token_auth/pull/1075#issuecomment-378779821)! It saved a lot of debugging time ❤️ 

I really like how simple devise controller looks using [`#errors`](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/confirmations_controller.rb#L26) hope to see it one day here also :) 

I just came here to say that currently if the user was already confirmed we are returning an expired token. However, it makes more sense to return 422 error I believe. BTW, original devise action [does just that](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/confirmations_controller.rb#L30).

**Comment by mathportillo** [comment] 2018-10-08 18:48
I am dealing with confirmation in my projects right now, and have two comments:

- clicking on the confirmation link a second time, results in generating a token that does not work. It should work or do not generate at all if the confirmation link is "used". When my rails server redirects to my web app, the web app has no way of knowing if the confirmation link was used first or second time, neither if the headers provided will work or not (prior to using it and failing/succeeding). 

- I feel bad about auth headers showing auth headers as query params on the confirmation landing page. I think the proper way to confirm an email is to redirect to the front-end with a token and from there make an AJAX request to confirm the token. This is slightly more work but makes more sense to me.

The first item may be an unrelated bug and if so can be disconsidered.
The second item may be a behaviour to be discussed in another issue, and if so should be disconsidered.
Regardless, I found it wouldn't hurt to describe both here because maybe it can help Evan in his implementation

**Comment by experimatt** [comment] 2020-01-30 16:11
+1 I just encountered this issue. I feel like more gracefully handling when a confirmed user clicks the confirm email link a second time would be a significant improvement.

**Comment by gamesover** [comment] 2021-02-07 14:44
meet this issue.

I have a feeling that both devise and devise_token_auth are no longer actively maintained. 
The two are wonderful gems for rails.

**Comment by MaicolBen** [comment] 2022-12-27 22:35
Resolved by #1157

**Closed by MaicolBen** 2022-12-27 22:35 UTC
Labels: request for comments
