### ISSUE TITLE
Password gets updated but current password is still invalid.

### ISSUE THREAD

**Issue by meta-akshat-mathur** [lynndylanhurley/devise_token_auth#836] opened 2017-02-23 06:48 UTC
I am using devise (4.2.0) and devise_token_auth(0.1.40)
When I change password for user, I have send (current_password,password,password_confirmation) ,
If the current password is invalid it returns an error but at the same time it updates the password for the user. Please check

**Comment by sivagollapalli** [comment] 2017-03-20 12:25
@meta-akshat-mathur Could you provide a sample program to reproduce this issue?

**Comment by zachfeldman** [comment] 2017-10-07 17:57
Closing due to lack of more information

**Closed by zachfeldman** 2017-10-07 17:57 UTC
