### ISSUE TITLE
Rails 5 - Missing template devise_token_auth/registrations/create

### ISSUE THREAD

**Issue by hoanghiep90** [lynndylanhurley/devise_token_auth#598] opened 2016-04-03 17:58 UTC
I used rails g devise_token_auth:install User auth so I have mount_devise_token_auth_for in my config/routes.rb. Like this

```
namespace :api, defaults: {format: 'json'} do
    scope :v1 do
      mount_devise_token_auth_for "User", at: 'auth'
    end
  end
```

My gem:

```
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0.beta'
# Fix issues https://github.com/plataformatec/devise/issues/3736
gem 'devise', github: 'plataformatec/devise', branch: 'master'
gem 'omniauth', '>= 1.0.0'

# Token based authentication for Rails JSON APIs
gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth', branch: 'master'
```

When I request: `http://192.168.99.100:3000/api/v1/auth` ( by POSTMAN )

I get an errors:

```
rb_1     | Started POST "/api/v1/auth" for 192.168.99.1 at 2016-04-03 15:55:18 +0000
rb_1     |   ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
rb_1     | Processing by DeviseTokenAuth::RegistrationsController#create as JSON
rb_1     |   Parameters: {"email"=>"hiep.nguyen"}
rb_1     | Unpermitted parameter: format
rb_1     | Unpermitted parameter: format
rb_1     | Unpermitted parameter: format
rb_1     | Completed 500 Internal Server Error in 37ms (ActiveRecord: 2.1ms)
rb_1     | 
rb_1     | 
rb_1     | 
rb_1     | ActionView::MissingTemplate - Missing template devise_token_auth/registrations/create, devise_token_auth/application/create, devise/create, application/create with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
rb_1     |   * "/gems/gems/devise_token_auth-0.1.37/app/views"
rb_1     |   * "/gems/bundler/gems/devise-2b3799e6ceb3/app/views"
```

Does anyone have any idea?

**Comment by grantsprunger** [comment] 2016-04-09 15:14
The problem seems to be caused by jbuilder. Changing the jbuilder gem source to the git master branch gem 'jbuilder', :git => 'git://github.com/rails/jbuilder.git' fixed the problem for me.

**Comment by edwardvalentini** [comment] 2016-04-09 20:09
So i had this problem because i was using rails5 with api only.   When i changed my `application.rb` to say
```
    config.api_only = false
```
then it works ok... 

@lynndylanhurley - is this supposed to be the case?  can we not use devise_token_auth with rails --api ?

**Comment by tpetrone** [comment] 2016-06-19 22:34
@grantsprunger: Wish I had stumbled on this sooner. Thank you!

**Comment by zachfeldman** [comment] 2017-10-07 15:05
Seems like we have a proposed solution here, so closing for now.

**Closed by zachfeldman** 2017-10-07 15:05 UTC
