### ISSUE TITLE
'no implicit conversion of Hash into String (TypeError)' on Travis CI

### ISSUE THREAD

**Issue by Dschee** [lynndylanhurley/devise_token_auth#365] opened 2015-08-31 01:50 UTC
I'm currently working on an [open source project](https://github.com/Flinesoft/MovieAssistor) where I use this gem alongside Devise. In my `User` class I included the following:

``` ruby
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable
  include DeviseTokenAuth::Concerns::User
```

I'm also using FactoryGirl in order to lint all my factories and added some specs to my project. When I run `rspec` on my development machine (tested with Ruby 2.1.7 and Ruby 2.2.2) then **all specs pass successfully**. But when I push my changes and things are run **on Travis CI** then **I get the following error message**:

``` ruby
/home/travis/build/Flinesoft/MovieAssistor/vendor/bundle/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/linter.rb:14:in `lint!': The following factories are invalid: (FactoryGirl::InvalidFactoryError)
* user - no implicit conversion of Hash into String (TypeError)
```

First I thought there's something wrong with my models. But after a few hours of trial-and-error style debugging I managed to locate **the part that's causing this error**: It's the above quoted code where I include the Devise and DeviseTokenAuth stuff into my `User` model.

I assume so because [this commit](https://github.com/Flinesoft/MovieAssistor/commit/281be3282307eb22a14ada5466ebda3647942c6a) fails on Travis CI (as you can see [here](https://travis-ci.org/Flinesoft/MovieAssistor/builds/77975944)) but the project was passing right before that commit (which you can see [here](https://travis-ci.org/Flinesoft/MovieAssistor/builds/77975870)). 

Therefore my best guess is that something in this gem (or maybe even Devise directly?) is causing things to break on Travis CI. As it feels like a bug to me I'm posting this here instead of StackOverflow.

Feel free to checkout the 'fix-travis-ci-tests' branch in order to investigate further if needed.

I'm using v0.1.34 of devise_token_auth in a Rails 4.2.4 project.

**Comment by Dschee** [comment] 2015-09-08 16:09
I succeeded in replicating this issue on my development machine, too now. When I run `rake db:drop db:create db:migrate db:seed` and then `rspec` I get the same error as I get on Travis CI. When I though do `rake db:reset` or `rake db:drop db:create db:schema:load db:seed` and then run `rspec` then everything succeeds again.

I really don't know where this comes from but as a workaround I have simply changed my `.travis.yml` file to state:
``` YAML
script:
  - bundle exec rake db:schema:load db:seed
  - bundle exec rspec
```

With this workaround my tests pass – but I wonder why `db:migrate` doesn't seem to work...

**Comment by ArneZsng** [comment] 2015-09-11 13:55
I currently have a similar issue when running `rake db:drop db:create db:migrate db:populate` in one line. Strangely it works if I run `rake db:drop db:create db:migrate` and then `rake db:populate` after. 


In this case, it fails due to:
```
TypeError: no implicit conversion of Hash into String
in
gems/devise_token_auth-0.1.34/app/models/devise_token_auth/concerns/user.rb:234:in `set_empty_token_hash'
```

I noticed that I have an earlier model identified by devise_token_auth with a column t.text for tokens which works fine, while the new migration for another model created a json column which fails in this scenario. 

The decision for the column type is in 
devise_token_auth/test/dummy/db/migrate/20140715061447_devise_token_auth_create_users.rb
```
      ## Tokens
      if json_supported_database?
        t.json :tokens
      else
        t.text :tokens
      end
```

**Comment by adamhunter** [comment] 2015-09-13 21:35
:+1: replicated when running `bin/rake db:drop db:create db:schema:load db:seed`.  Everything works perfectly if I run `bin/rake db:drop db:create db:schema:load && bin/rake db:seed`.  I assume this must have something to do with the active record connection cache when referencing json columns.  That is just a stab in the dark though.

**Comment by premosystems** [comment] 2015-11-05 19:30
I had this same problem using RubyMine, killing spring and restarting RubyMine did the trick. Would never have figured it out without this post. Thanks!

**Comment by ryaz** [comment] 2016-01-13 00:20
+1 to @adamhunter

**Comment by Fudoshiki** [comment] 2016-01-13 07:11
I have this issue too with gem spring
rake db:setup 
```
-- create_table("users", {:force=>:cascade})
   -> 0.0062s
-- add_index("users", ["confirmation_token"], {:name=>"index_users_on_confirmation_token", :unique=>true, :using=>:btree})
   -> 0.0025s
-- add_index("users", ["email"], {:name=>"index_users_on_email", :using=>:btree})
   -> 0.0029s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true, :using=>:btree})
   -> 0.0053s
-- add_index("users", ["uid", "provider"], {:name=>"index_users_on_uid_and_provider", :unique=>true, :using=>:btree})
   -> 0.0056s
-- add_index("users", ["unlock_token"], {:name=>"index_users_on_unlock_token", :unique=>true, :using=>:btree})
   -> 0.0030s
-- initialize_schema_migrations_table()
   -> 0.0071s
rake aborted!
TypeError: no implicit conversion of Hash into String
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/json/decoding.rb:26:in `decode'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/coders/json.rb:9:in `load'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/type/serialized.rb:19:in `type_cast_from_database'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/type/mutable.rb:5:in `type_cast_from_user'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:110:in `type_cast'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:42:in `original_value'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:37:in `value'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:50:in `changed_from?'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:142:in `_field_changed?'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:115:in `save_changed_attribute'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:98:in `write_attribute'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods.rb:50:in `__temp__47f6b656e637'
/Users/user/.rvm/gems/ruby-2.3.0/gems/devise_token_auth-0.1.36/app/models/devise_token_auth/concerns/user.rb:235:in `set_empty_token_hash'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `block in call'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `each'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_initialize_callbacks'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/core.rb:284:in `initialize'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:61:in `new'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:61:in `new'
/Users/user/Repository/work/curious-backend/db/seeds.rb:5:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:547:in `load_seed'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/user/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:seed
```

**Comment by itsthatguy** [comment] 2016-03-01 17:13
### solved

If using `postgres 9.4.4+` in your `devise_token_auth` migration for users, change `t.json :tokens` to `t.jsonb :tokens`

Good luck!

**Comment by itsthatguy** [comment] 2016-03-01 17:29
With the `devise_token_auth` migration for users, changing `t.json :tokens` to `t.string :tokens` seems to fix the issue.

I haven't confirmed that this will work for authentication, but given all of the column type checking (ie; https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L26-L28) I am lead to believe it might.

**Comment by artemv** [comment] 2016-06-21 22:12
+1 to @itsthatguy, confirm that this change works for auth, at least with Postgres - some DBs will be better with :text for that like @anthonynavarre did above

**Comment by prusswan** [comment] 2017-03-02 04:08
Ran into this problem on the Trusty (beta) using Postgres 9.5
Resolved by creating the database, followed by `bundle exec rake db:schema:load`

**Comment by zachfeldman** [comment] 2017-10-07 14:03
Seems like this problem has an accepted solution, so closing for now.

**Closed by zachfeldman** 2017-10-07 14:03 UTC
