### ISSUE TITLE
Use with existing User model

### ISSUE THREAD

**Issue by bazalel** [lynndylanhurley/devise_token_auth#701] opened 2016-08-15 14:54 UTC
Can I use devise token auth with an existing user model?

Can I run the instal command so that updates my existing users' table instead of creating a new one?

**Comment by zachfeldman** [comment] 2017-10-07 15:32
Hi there @bazalel    ,

In an effort to cleanup this project and prioritize a bit, we're marking issues that haven't had any activity in a while with a "close-in-7-days" label. If we don't hear from you in about a week, we'll be closing this issue. Obviously feel free to re-open it at any time if it's the right time or this was done in error! 

If you are still having the issue (especially if it's a bug report) please refer to our new [Issue Template](https://github.com/lynndylanhurley/devise_token_auth/blob/master/.github/ISSUE_TEMPLATE.md) to provide some more details to help us solve it.

Hope all is well.

**Closed** 2017-10-14 14:44 UTC
Labels: close-in-7-days

**Comment by karlingen** [comment] 2017-11-09 17:48
https://github.com/lynndylanhurley/devise_token_auth/wiki/Setup-migrations-for-an-existing-User-table

**Comment by frizman21** [comment] 2020-05-17 22:33
duplicate of #181
