### ISSUE TITLE
@resource.allow_password_change is not persisted across requests

### ISSUE THREAD

**Issue by Chosko** [lynndylanhurley/devise_token_auth#481] opened 2015-12-21 16:00 UTC
My application is set to require current_password when users want to change their password.
The problem is when an user wants to reset the password. After the mail is sent and the user is prompted to insert the new password, the server returns 422 with the error: "current_password can't be blank".

I'm using v0.1.37.beta4, and this version contains a pull request: https://github.com/lynndylanhurley/devise_token_auth/commit/d33bcdb5bae993bd4ba8134b52486c8b6cce2908
which is supposed to fix this problem, but it doesn't.

I guess the problem here is that @resource.allow_password change is set to true in projects_controller#edit but it's not persisted to the DB, and in the next call (projcets_controller#update) its value is false again.

I made a quick and dirty fix to store allow_password to the DB, though I'm not sure it's a good solution because this means changing the generators too....
I don't have the time to implement tests, so I didn't even open the PR. However, you can see the changes here https://github.com/Chosko/devise_token_auth/commit/e3a4d3d888547662352c8bc4568ddab6b84ac259.

**Comment by biomancer** [comment] 2016-02-01 14:26
I suppose we can fix that without flag persistence by passing `reset_password_token` to redirect url and checking it again in `update` action. I am using currently a quick fix which is below, it can be done cleaner and some checks are required, but I can't find now a minute to prepare proper fix and PR, so I hope it may help someone:

While using custom passwords controller
```
class PasswordsController < DeviseTokenAuth::PasswordsController

 def edit
   super do # TODO there is minor bug too - block does not pass resource        
     # TODO build url correctly when it already has some params (I did not need it in my case)
     params[:redirect_url] += "?reset_password_token=#{@resource.reset_password_token}"
   end
 end

 protected 

 def resource_update_method
    @resource.allow_password_change = @resource.reset_password_token.present? && resource_params[:reset_password_token] == @resource.reset_password_token
    super
 end

end
```

That will change interface for PUT /auth/passwords, requiring to pass `reset_password_token` when there is no current password specified.

**Comment by paulius005** [comment] 2016-02-08 09:33
I added a simple `allow` flag that I am passing in when i call update, also not the best solution, but it works for now

**Comment by paulius005** [comment] 2016-02-08 09:34
This seems to be the same as #526 I should probably close mine

**Comment by biomancer** [comment] 2016-02-08 09:51
@paulius005 using some flag param is less secure, as one may update password without knowing old password or reset token, which should not happen as I suppose. That does not look like serious issue as user still must be authorized at this point, but reusing reset token instead of flag solves it anyway, so why not use it.

**Comment by paulius005** [comment] 2016-02-08 09:54
Yep! Agreed

**Comment by bobmshannon** [comment] 2016-04-06 16:22
Having this same issue, but none of the fixes mentioned here worked for me. Using the master branch of device token auth and rails 5 beta 3.

**Comment by Stex** [comment] 2016-06-01 11:12
I extended @biomancer's solution a bit to support URLs with already existing parameters:

```ruby
class Api::PasswordsController < DeviseTokenAuth::PasswordsController
  def edit
    super do
      redirect_url          = URI.parse(params[:redirect_url])
      reset_params          = {reset_password_token: @resource.reset_password_token}
      redirect_url.query    = Rack::Utils.parse_query(redirect_url.query).merge(reset_params).to_query
      params[:redirect_url] = redirect_url.to_s
    end
  end

  def update
    @resource.allow_password_change = valid_reset_password_token?
    super
  end

  protected

  def valid_reset_password_token?
    @resource.reset_password_token.present? && resource_params[:reset_password_token] == @resource.reset_password_token
  end
end
```

**Comment by volfgox** [comment] 2016-09-04 10:25
I tested the above solutions suggested by @Stex  and @biomancer. The problem still persisted for me. So, I decided to add an additional persistent allow password change field to user model. My solution is:

```ruby
class AddPersistentAllowPasswordChangeToUsers < ActiveRecord::Migration
  def change
  	add_column :users, :persistent_allow_password_change, :boolean, null: false, default: false, after: :reset_password_sent_at 
  end
end
```

Then, I override passwords controller of `devise_token_auth` as bellow:

```ruby
module Api
  module V1
    module Overrides
      class PasswordsController < DeviseTokenAuth::PasswordsController
        def edit
          super do |resource|
            resource.persistent_allow_password_change = true
            resource.save!
          end
        end

        def update
          super do |resource|
            resource.persistent_allow_password_change = false
            resource.save!
          end
        end

         protected 

           def resource_update_method
             @resource.allow_password_change = @resource.persistent_allow_password_change
             super
           end
      end
    end
  end
end
```

And, I changed devise_token_auth routes in `routes.rb` as below:

```ruby
mount_devise_token_auth_for 'User', at: 'auth', controllers: {
  sessions:	'api/v1/overrides/sessions',
  omniauth_callbacks: 'api/v1/overrides/omniauth_callbacks',
  registrations: 'api/v1/overrides/registrations',
  passwords: 'api/v1/overrides/passwords'
}
```

With this solution, every time user redirected from reset password email to application, when edit action of `PasswordsController` is executed, `persistent_allow_password_change` is set to `true`. When update password request of client receives the server, the value of `persistent_allow_password_change` is assigned to `allow_password_change` in `resource_update_method`, before `super`. After password changing in `update` action, the value of `persistent_allow_password_change` is reset to `false`.

**Comment by zachfeldman** [comment] 2017-10-07 14:30
Sounds like we have an accepted solution here, so closing this for now!

**Closed by zachfeldman** 2017-10-07 14:30 UTC

**Comment by sickrandir** [comment] 2017-11-22 11:37
Is it fixed upstream in some released version?

**Comment by zachfeldman** [comment] 2017-11-22 14:18
@sickrandir it might be, we are testing this release right now:
https://github.com/lynndylanhurley/devise_token_auth/tree/v0.1.43.beta1

which is the latest. If not feel free to submit a pull request!

**Comment by sickrandir** [comment] 2017-11-22 14:24
@zachfeldman thanx. I installed 0.1.43.beta1 and I can confirm that it fixes this issue for me.

**Comment by zachfeldman** [comment] 2017-11-22 14:26
That's great!
