### ISSUE TITLE
support for multiple client_id

### ISSUE THREAD

**Issue by kascote** [lynndylanhurley/devise_token_auth#535] opened 2016-02-11 19:35 UTC
On SessionController#create a new client_id is generated for a every successful login. But the docs states:

> **Client**: This enables the use of multiple simultaneous sessions on different clients. (For example, a user may want to be authenticated on both their phone and their laptop at the same time.)
> [link](https://github.com/lynndylanhurley/devise_token_auth#token-header-format)

I'm missing something or how is suppose to use this param ?

TIA

**Comment by ashwinputhige** [comment] 2016-08-27 05:16
@kascote Did you figure this out?

**Comment by adisos** [comment] 2016-08-27 06:04
After you signed in, server returns headers. Just use access-token, client and uid. Or you meant something else? I don't get your question.

**Comment by ashwinputhige** [comment] 2016-08-27 06:08
@kascote , The issue is that I am not able to keep multiple sessions alive. If I login from my laptop  and then login using my phone, I get logged out from the laptop. At any time, I can have only one session alive for the user.
How do you allow user to be authenticated from phone and laptop simultaneously?

**Comment by adisos** [comment] 2016-08-27 06:43
@ashwinputhige 
I don't really know why it's not working for you, but look at demo [here](https://j-toker-demo.herokuapp.com/#/). It's working fine.

**Comment by joyeux7** [comment] 2016-10-25 11:29
Not sure if it can help you

https://github.com/lynndylanhurley/devise_token_auth/issues/680

**Comment by zachfeldman** [comment] 2017-10-07 14:39
Seems like we have a solution for this, so closing for now.

**Closed by zachfeldman** 2017-10-07 14:39 UTC
